[workspace]
[package]
name = "tari-stable-coin"
version = "0.1.0"
edition = "2024"
description = "Private stable coin with user badge"

[package.metadata.tari-template]
tags = ["token", "stablecoin", "stable-coin", "defi", "fungible", "privacy"]
category = "stable-coin"

[dependencies]
tari_template_lib = { version = "0.27", default-features = false, features = ["macro", "alloc"] }
minicbor = { version = "2.2.2", default-features = false, features = ["derive", "alloc"] }
talc = { version = "5.0", default-features = false }

[dev-dependencies]
tari_template_test_tooling = "0.31"
ootle_byte_type = "0.8"

[profile.release]
opt-level = 's'     # Optimize for size.
lto = true          # Enable Link Time Optimization.
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic.
strip = true

[lib]
crate-type = ["cdylib"]

[build-dependencies]
tari_ootle_template_build = "0.7"
